version: '3'

services:
  onlinesurvey:
    image: yont/onlinesurvey:v1.0.0
    container_name: onlinesurvey
    restart: always
    environment:
      - MYSQL_HOST=onlinesurvey-mysql
      - MYSQL_USER=survey
      - MYSQL_PASSWORD=survey
    ports:
      - 80:80
    networks:
      - osv_net
    depends_on:
      - onlinesurvey-mysql
  onlinesurvey-mysql:
    # image: mysql:8.0.23
    image: mysql:5.7
    container_name: onlinesurvey-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - MYSQL_DATABASE=surveydb
      - MYSQL_USER=survey
      - MYSQL_PASSWORD=survey
      - MYSQL_ROOT_PASSWORD=123qwe
    command:
      - mysqld
      # - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      # - /opt/onlinesurvey/mysql:/var/lib/mysql
      - ./surveydb.sql:/docker-entrypoint-initdb.d/surveydb.sql
    networks:
      - osv_net

networks:
  osv_net:
    driver: bridge
